import type { Metadata } from "next";
import './globals.css'
import { Outlet } from "react-router-dom";

export const metadata: Metadata = {
  title: "fishpond@EA",
  description: "Generated by create next app",
};

export default function RootLayout() {

  return (
    <>
      <Outlet />
    </>
  )
}
